### ISSUE TITLE
Improve icons

### ISSUE THREAD

**Issue by gingerbeardman** [gingerbeardman/stapler#1]
Given that the app was made in a day I ran out of steam whilst creating the icon. Could be better. 

## Better icons

- better icon for Stapler.app
- StaplerDocument icon

## Idea

I have a very specific idea for the icon. The stapler should be viewed from the side and take up the whole of the rounded rectangle icon shape.

Also, I'll need the source files of the illustration so that I can optimise and prepare the various icon sizes required for a modern macOS app.

## Request

Please get in touch before proposing designs. 

## Existing icon

It's literally 4 rounded rectangles and a circle, and two rectangles for the background. 😬

<img width="824" alt="Icon Artwork" src="https://github.com/user-attachments/assets/16a88e77-6c6c-4a42-a4d9-170d8c70cd1b">

**Comment by bestguy** [comment]
Hi, if something like this looks okay, please let me know image dimension(s) or format you need:

![stapler-768](https://github.com/user-attachments/assets/b93eb26c-108e-456a-b0c0-019a2d07d3a8)

**Comment by maxtron95** [comment]
Created an icon. I also included an center image icon for the document file in the zip.

![stapler](https://github.com/user-attachments/assets/a46bd9be-69da-4617-a868-ccdd5248a1eb)


[stapler-icon.zip](https://github.com/user-attachments/files/16573188/stapler-icon.zip)

**Comment by gingerbeardman** [comment]
@maxtron95 @bestguy thanks both. 

I have a very specific idea for the icon. That the stapler should be viewed from the side and take up the whole of the rounded rectangle icon shape. 

Also, I'll need the source files of the illustration so that I can optimise and prepare the various icon sizes required for a modern macOS app.

**Comment by rorz** [comment]
Something like this?
<img width="512" alt="stapler" src="https://github.com/user-attachments/assets/e71b062c-5226-4d6a-9ea0-733a2719a863">

**Comment by gingerbeardman** [comment]
I have a designer working on this, so will close this issue for now. Thanks everybody.

But @rorz to answer your query above... no. :)

My thinking was that the stapler would take up the whole round rect. A quick google shows:

![JTCZ9K5Q](https://github.com/user-attachments/assets/88e8161a-2909-42cb-a573-e1106bb770b8)
