### ISSUE TITLE
Using Cmd+O to open document from Finder can unintentionally trigger edit mode

### ISSUE THREAD

**Issue by rcarmo** [gingerbeardman/stapler#10]
I would suggest using Option to open documents in edit mode, since I use Cmd+O to open things from the Finder routinely and, of course, Stapler launches so fast that it detects Cmd is down and thinks I want to edit the document rather than launch the list of items.

**Comment by gingerbeardman** [comment]
Hey Rui!

I had contemplated this, but my reasoning for using Cmd is that you would purposefully open with Cmd+O (or Cmd+down cursor) and leave your finger/thumb on Cmd to go into edit mode. I think it feels good that way, like it's truly a modifier of the open operation.

If I ever add per-document settings (no plan right now, but never say never) I'll add this as an option. It's on my todo list (btw I use Taskpaper for these) and so I'll close this issue for now.

Cheers!

**Comment by rcarmo** [comment]
I would urge you to reconsider, since I use macOS almost exclusively via a keyboard. Hitting Return invariably has me renaming files, so Cmd+O is the only way I can reliably open documents).

**Comment by gingerbeardman** [comment]
I'll definitely give it some thought. I'm also interested if anybody else has this issue. I'll be sure to point them here if so.

Currently I'm thinking:
1. allow use of Cmd or Option to enter edit mode (would not solve your problem, but would not beak behaviour)
2. add a small delay on launch for user to let go of Cmd (how long do you keep Cmd/O press during opening?)
3. some sort of hidden prefs for experimental features or certain use cases

**Comment by gingerbeardman** [comment]
Of course! Just trying to figure out how much of a delay to perhaps put in the launch process. 0.25s?

**Comment by rcarmo** [comment]
We can start with that. You can make it a .plist item (it's been a while since I dealt with AppKit/Swift on macOS, but setting a default should be a one-liner and you don't really need to build a UI for it)

**Comment by gingerbeardman** [comment]
Please give version 1.2.3 (pre-release) a try: https://github.com/gingerbeardman/stapler/releases/tag/1.2.3

I added a page to the wiki showing [how to set/read/delete the delay](https://github.com/gingerbeardman/stapler/wiki/Experimental-options#wait-before-reading-command). Default wait is 100 ms.

**Comment by rcarmo** [comment]
Hi! Tried it, and I'm setting it to 500ms. I tend to leave my finger on Command because I typically open stuff and Command-Tab to and fro.

**Comment by gingerbeardman** [comment]
Cool! Glad this workaround works for you.
