### ISSUE TITLE
Document Icon is blank

### ISSUE THREAD

**Issue by rcarmo** [gingerbeardman/stapler#11]
Somehow I can't see any document icons for Stapler, so I took 30m off my lunchtime, looked at the Apple Design Guidelines, and ground these out. The app icon is based on a Bing Image Creator generation with a mask applied, and as such is automatically free to use. The document icon was created by just flipping the blank document icon around and rotating it around, plus adding the usual file type text overlay in SF Pro font.

Feel free to use them (or not), but I had fun creating them :)

![app](https://github.com/user-attachments/assets/011a917a-6566-4b4c-9a94-735ee33722e9)
![document](https://github.com/user-attachments/assets/23607618-c359-4ec6-8598-8df0658d8069)

**Comment by gingerbeardman** [comment]
Thanks! I have a designer working on the icons right now.

I do like your document icon, but I have a very specific idea for the app icon.

https://github.com/gingerbeardman/stapler/issues/1

**Comment by gingerbeardman** [comment]
Reopening until this one is solved by the forthcoming icons

**Comment by gingerbeardman** [comment]
Work for this has been done.

Awaiting new icons from my designer.

**Comment by rcarmo** [comment]
I'm still not seeing a document icon in 1.2.3, even after making sure I deleted the old version

**Comment by gingerbeardman** [comment]
Try doing get info on the file to refresh its icon.
