### ISSUE TITLE
Can't Run on Sequoia (Not Notarized?)

### ISSUE THREAD

**Issue by mierau** [gingerbeardman/stapler#12]
Here's a screenshot of the window in Sequoia I see when running Stapler. Is Stapler notarized? This shows if I open from Finder or context menu. I don't recall seeing a dialog like this pre-Sequoia when I could force it open.

<img width="372" alt="Screenshot 2024-08-13 at 3 43 20 PM" src="https://github.com/user-attachments/assets/bdc23369-ee20-4e43-a42a-2d9fac751dbf">

**Comment by gingerbeardman** [comment]
Yeah this is Sequoia being awkward.

I believe there are extra steps needed to run such an app https://www.reddit.com/r/MacOSBeta/comments/1dd8f1y/nonnotarised_apps_much_harder_to_open_in_macos/

There's an Alfred workflow to do the above, or you can roll your own solution.

I have no plans to notarise the app at this time.

**Comment by mierau** [comment]
I'm curious why you don't want to notarize. Not a judgement just genuinely curious. Hotline is notarized because I feel like the system adds a level of legitimacy for the user, but maybe I'm missing something. :)

**Comment by gingerbeardman** [comment]
No real reason, only that I've never notorized anything before and there is a lot on my todo list :)

**Comment by mierau** [comment]
Ah got it. Yeah it's a bit weird in Xcode seems like it should be more straightforward. Let me know if I can help but it's basically the same as producing a build for distribution with a few more checks.

**Comment by gingerbeardman** [comment]
Well, i didn't realise it was literally a one click from the Archive Organiser.

Will upload a 1.2.1 to give it a whirl

**Comment by gingerbeardman** [comment]
https://github.com/gingerbeardman/stapler/releases/tag/1.2.1
