### ISSUE TITLE
Better way to tell if Document was launched from Finder

### ISSUE THREAD

**Issue by gingerbeardman** [gingerbeardman/stapler#2]
Currently the code to figure out whether the Stapler Document was opened from Finder is not really very good. 

Basically, we're checking if the app is activated. That works, because the app does get activated when coming from Finder, but there are other ways the Document can be opened that result in the app being Activated.

```swift
let currentEvent = NSApplication.shared.currentEvent
let eventTypeValue = currentEvent?.subtype.rawValue
let isOpenedFromFinder = currentEvent != nil && currentEvent?.type == .appKitDefined && eventTypeValue == 1

// NSEvent.EventSubtype.applicationActivated == 1
```

So, we need to find a better way to do this. I ran out of time at this point.

**Comment by gingerbeardman** [comment]
Improved in https://github.com/gingerbeardman/stapler/commit/04398d830999ab03d37ac0430f6c9a5c20ee7030

Coming in 1.2

**Comment by aptonline** [comment]
Hi, this is still not working for me even from a cold start of the app. Same result. no documents opening.

**Comment by gingerbeardman** [comment]
Small change: https://github.com/gingerbeardman/stapler/commit/feaa002287e82e1d13f4cc4aac7ef4a35030c9c4

Will live with this for a while.

**Comment by gingerbeardman** [comment]
Reworked around https://github.com/gingerbeardman/stapler/commit/9fad23ce1ce9680f99ec9e1063e014b6a9a4d9db to check for the following scenarios: 

```swift
// Define an enum for the different document opening scenarios
enum DocumentOpeningScenario {
	case launchedWithDocument
	case resumedBySystem
	case openedThroughFileMenu
	case openedFromFinderWhileRunning
	case unknown
}
```
