### ISSUE TITLE
Double-clicking a list item should launch it

### ISSUE THREAD

**Issue by runxel** [gingerbeardman/stapler#4]
First off: Nice app!

I think it is unintuitive that a double click does nothing to a document. It should open the corresponding file / app.

**Comment by gingerbeardman** [comment]
By design, double-clicking a document will launch all items in it. 

To edit a document you can hold down the Cmd key as you open it. 

I understand this is perhaps a contentious issue. I'll give it some thought.

**Comment by runxel** [comment]
For most documents having quicklook should already covers the use case.
What I meant was: While editing a stapler doc double-clicking in the list should open just that doc. But I agree that this is not really the main thing of stapler. (:

**Comment by gingerbeardman** [comment]
Oh, right! I misunderstood.

Yes, I agree.

I'll make the change soon :)

**Comment by gingerbeardman** [comment]
Added in https://github.com/gingerbeardman/stapler/commit/6a74086b2c85c5b35e329ae08f0c2309e524c96c

New version will release "soon"

**Comment by gingerbeardman** [comment]
Added in 1.2 https://github.com/gingerbeardman/stapler/releases/tag/1.2
