### ISSUE TITLE
Open certain page in a PDF

### ISSUE THREAD

**Issue by runxel** [gingerbeardman/stapler#41]
A bit like #36, but for pages of a PDF document. 
Do you think this is possible? Probably depends on the app opening it.

**Comment by gingerbeardman** [comment]
Out of scope, I would say. Sorry.

Preview remembers this info in `com.apple.Preview.ViewState.plist` but of course you need to have already looked at that PDF on that machine to that page.

You could add a script to go to a specific page of the PDF that has been opened.
