### ISSUE TITLE
Shutting down Stapler gives no "save warning" dialog

### ISSUE THREAD

**Issue by runxel** [gingerbeardman/stapler#5]
When you (accidentally) close Stapler there should be a warning dialog so you can save the stapler doc and not lose your work.

**Comment by gingerbeardman** [comment]
Thanks for the report. 

This is absolutely an oversight on my part. 😳

You might wonder how I vouod miss this? Well, I have my Mac set to remember and restore the windows of any app that are open when it is closed. This basically gives you permanence for free. I've had my system set this way for so long I forgot that it's not the default. 

I just added this to the blog post:

> System Preferences > General > Desktop & Dock > Windows > Close windows when quitting an application = OFF
> 
> Then leave the windows of an app open as you quit it. When you next launch the app its windows will restore to their previous size and position. If you close the windows first, then the app will restore to having no windows open.

**Comment by gingerbeardman** [comment]
Currently my workaround is to just save the files when you quit. Not ideal. Will try a better approach before I launch 1.1.0

**Comment by gingerbeardman** [comment]
Solved in 1.1 https://github.com/gingerbeardman/stapler/releases/latest

If you're still having related issues, feel free to comment here.
