### ISSUE TITLE
Does not prompt for permission in some places.

### ISSUE THREAD

**Issue by paalb** [gingerbeardman/stapler#6]
I get a prompt and it opens the file in downloads. But not the one in miniconda3. 
<img width="653" alt="Screenshot 2024-08-11 at 21 37 40" src="https://github.com/user-attachments/assets/4a53614e-785a-427f-97a9-1a541a680688">

And not the files in Diverse
<img width="895" alt="Screenshot 2024-08-11 at 21 19 03" src="https://github.com/user-attachments/assets/4759ae61-5377-4df4-b565-02ac5e30dfcf">

<img width="1228" alt="Screenshot 2024-08-11 at 21 25 53" src="https://github.com/user-attachments/assets/04aa24d2-a8a2-4e2c-a34d-20605e6d4750">

**Comment by gingerbeardman** [comment]
You need to give the app extra access permissions in `System Settings > Privacy & Security > Files & Folders`

or, after you've inspected the code and are comfortable the app doesn't do anything untoward, you could go to `System Settings > Privacy & Security > Full Disk Access` and add it there so you're never bothered again for this app.

By default I only gave it access and the ability to prompt for access to the most common recommended folders. That's basically Downloads, Documents, and the user selected locations. 

Without the additional permissions might see different behaviour adding files through the file selector than drag and drop.

**Comment by invig** [comment]
Love the idea, thanks for open sourcing! 

- `System Settings > Privacy & Security > Files & Folders` this isn't possible on MacOS Sonoma as far as I can tell, if the application doesn't prompt there is no way to manually grant it permissions to specific places. For me this resulted in silent failure to launch things.
- `System Settings > Privacy & Security > Full Disk Access` this sort of works, but for many things launch will still fail, for example if I install a website as an app using Safari I'll get an error like this when Stapler tries to launch it:
![Screenshot by Dropbox Capture](https://github.com/user-attachments/assets/817b2bda-b923-4849-b285-3f23480441e0)

**Comment by gingerbeardman** [comment]
Something odd going on here, as I am developing it on Sonoma.

- `System Settings > Privacy & Security > Files & Folders` good point, this will only show directories the app has prompted for and you have approved (and this app will only prompt for Downloads, iirc)
- `System Settings > Privacy & Security > Full Disk Access` this should be enough.

Could it be that Stapler is running under App Translocation? Whilst it's not running, move it out of /Applications (to, say, ~/Documents) and then back to /Applications and then try again. Let me know.

Urgh, I do hate modern macOS "security" focus, it's so offensive to users and developers alike.

Here I am running a Google Sheets "Save to Dock" web app @invig 

https://github.com/user-attachments/assets/cead2216-4bb3-4aa2-a79f-82341e7d27cc

**Comment by gingerbeardman** [comment]
I'm going to add `com.apple.security.files.all` to the app entitlements.

This won't allow it on the Mac App Store, but I have no intention of submitting it so...

Will release in 1.2

**Comment by gingerbeardman** [comment]
Added in 1.2 https://github.com/gingerbeardman/stapler/releases/tag/1.2
