### ISSUE TITLE
The application “Stapler” does not have permission to open “(null)”

### ISSUE THREAD

**Issue by rcarmo** [gingerbeardman/stapler#9]
If I add an app (like Visual Studio Code) to a Staper document it gives this error message.

**Comment by gingerbeardman** [comment]
Please try the troubleshooting steps in this comment https://github.com/gingerbeardman/stapler/issues/6#issuecomment-2284942961

**Comment by gingerbeardman** [comment]
Good news! I've been able to set my system to reproduce this.

Will fix it as soon as possible.

**Comment by gingerbeardman** [comment]
please try 1.2.1 
- https://github.com/gingerbeardman/stapler/releases/tag/1.2.1

**Comment by gingerbeardman** [comment]
Phew! 

Fixed in 1.2.2
- https://github.com/gingerbeardman/stapler/releases/tag/1.2.2
